name: EdoMechanics
version: '${project.version}'
main: org.kayteam.edomechanics.EdoMechanics
api-version: 1.13
loadbefore: [ NBTAPI ]
depend: [ NBTAPI ]
authors: [ segu23, SirOswaldo ]
website: https://kayteam.org
commands:
  edomechanics:
    description: Main command
  test:
    description: test
