name: EdoMechanics
version: '${project.version}'
main: org.kayteam.edomechanics.EdoMechanics
api-version: 1.13
loadbefore: [ NBTAPI, PlaceholderAPI ]
depend: [ NBTAPI ]
softdepend: [ PlaceholderAPI ]
authors: [ segu23, SirOswaldo ]
website: https://kayteam.org
commands:
  EdoMechanics:
    description: ""
