items:
  mechanicsHeader:
    - "&6"
    - " &6&lITEM MECHANICS"
    - "&6"
  mechanic: " &f- &l&o%mechanic_name%"
  mechanicsFooter:
    - "&6"
    - " &7&oLeft Click to use mechanics"
mechanics:
  witherSkull:
    cooldown: 10
    minDamage: 5
    maxDamage: 10
    permissionToUse: "edomechanics.use.witherskull"
    permissionToBypassCooldown: "edomechanics.bypass.witherskull"
  shulkerBullet:
    cooldown: 10
    minDamage: 5
    maxDamage: 10
    permissionToUse: "edomechanics.use.shulkerbullet"
    permissionToBypassCooldown: "edomechanics.bypass.shulkerbullet"