package org.kayteam.edomechanics.mechanics;

public enum MechanicType {
    WITHER_SKULL, SHULKER_BULLET, POTION_EFFECT, LIGHTNING, FIREBALL, ARROW, EGG, SNOWBALL, TRIDENT, SMALL_FIREBALL, LARGE_FIREBALL, EXP_BOTTLE, DRAGON_FIREBALL, SPLASH_POTION, LINGERING_POTION
}
